#!/bin/bash

set -eo pipefail

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${currentDir}/../base.sh

CONNECTION_INFO_FILE=/tmp/$BUILDKITE_JOB_ID-connection-info

if [[ -f "$CONNECTION_INFO_FILE" ]]; then
    token=$(curl -m 60 -sd '{"email":'\"$ORKA_USER\"', "password":'\"$ORKA_PASSWORD\"'}' -H "Content-Type: application/json" -X POST $ORKA_ENDPOINT/token | jq -r '.token')
    trap 'revoke_token $token $ORKA_ENDPOINT' EXIT

    vm_id=$(<$CONNECTION_INFO_FILE)

    curl -m 60 -sd '{"orka_vm_name":'\"$vm_id\"'}' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -X DELETE $ORKA_ENDPOINT/resources/vm/delete
fi
