#!/bin/bash

set -eo pipefail

currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${currentDir}/../base.sh"

CONNECTION_INFO_FILE=/tmp/$BUILDKITE_JOB_ID-connection-info

if [[ -f "$CONNECTION_INFO_FILE" ]]; then
    vm_name=$(<"$CONNECTION_INFO_FILE")

    orka3 vm delete "$vm_name"
fi
