name: build

on:
  push:
    branch:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      env:
        SHELLCHECK_OPTS: "-P ./GitLab/scripts"
      with:
        scandir: './GitLab/scripts/'
        check_together: 'yes'
